version: '3'
services:

  app:
    build: ./
    environment:
      OTEL_SERVICE_NAME: "PetClinicWithAgent"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://collector:8317"
      # Logs are disabled by default
      OTEL_LOGS_EXPORTER: "otlp"
      # Digma entries
      CODE_PACKAGE_PREFIXES: "org.springframework.samples.petclinic"
      DEPLOYMENT_ENV: "SAMPLE_ENV"
    ports:
      - "9753:9753"
    depends_on:
      - collector

  collector:
    image: otel/opentelemetry-collector-contrib:0.66.0
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
    command: ["--config=/otel-config.yaml"]
    expose:
      - "8317"
    ports:
      - "8317:8317"
    extra_hosts:
      - "host.docker.internal:host-gateway"
