{{- if .Values.flaskdb.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flaskdb
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: {{ .Release.Name }}-flaskdb
  ports:
    - name: http
      protocol: TCP
      port: 27017
      targetPort: 27017

{{- end }}